### ISSUE TITLE
Hackaburg 2023 todos

### ISSUE THREAD

**Issue by AlexW00** [hackaburg/website#55]
# ToDos

## Mobile

- [x] Make font size smaller
- [x] Reduce whitespace
- [x] Directions and bus stop buttons are misaligned

### Main page

- [x] Discord invite link (footer) fixen (remove)
- [x] Hackaburg Logo in navbar clickable machen
- [x] Remove: 2G text
- [x] Make track text also clickable
- [x] (?) Andere Stock Fotos verwenden (ohne "adobe stock" text)
- [x] Resize starter images
- [x] Fav. Icon

### Track page

- [x] Fix: Navbar click action
- [x] Fix: Navbar click scrolls too far
- [ ] (?) Ausführlichere Track Beschreibung

### Green page

- [x] Farben der Überschriften anpassen (besser lesbar machen)
- [x] Fix: Navbar click scrolls too far
- [x] (?) Table oder cards statt headers mit bullet points

## Firefox

- [x] Fix "green.svg" zero width although it has "w-full" class; works in chrome 

## Other

- [x] green hightlight of "green" navbar item is confusing because it looks selected, fix by:
    - removing the highlight (easy)
    - changing the highlight on click & scroll (trickier)
- [x] typos

**Comment by marc101101** [comment]
green hightlight of "green" navbar item is confusing because it looks selected, fix by:
=> evtl. nicht grün, sondern nur grün bei hover und die anderen alle grau bei hover?

 Fix: Navbar click scrolls too far
=> Super nervig. evtl. noch das hier einfügen => https://www.w3schools.com/howto/howto_css_smooth_scroll.asp#section1

 (?) Andere Stock Fotos verwenden (ohne "adobe stock" text)
=> bin ich mit Ewald und der neuen Kreditkarte dran

**Comment by lat26358** [comment]
- [ ] Hackaburg 2016&17 in Footer rausnehmen
- [ ] Hackaburg 2022 Link anpassen (hackaburg.de -> hackaburg.de/2022)

**Comment by AlexW00** [comment]
- [ ] fix: Mobil Medium Logos genauso groß, wie die Premium (kleiner machen)
- [ ] die Links (in der Sponsoren-Liste hinterlegt)  einbauen
- [ ] Karte fixen (zoomed out)
